FROM golang:1.20.5-alpine3.18

RUN apk --no-cache add curl
WORKDIR /src

RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
  && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD air